vkcube & vkcubepp: Select physical device before create surface if platform is WSI Display
KhronosGroup/Vulkan-Tools pull request #1060
Opened 2024-12-16 09:17 UTC by water-chika

If platform is WSI Display, vkcube will use physical device when creating surface.

2024-12-16 09:19 UTC, water-chika commented
This PR fix https://github.com/KhronosGroup/Vulkan-Tools/issues/1056.

2024-12-16 15:43 UTC, charles-lunarg requested changes
Change looks decent, other than small grammar fixes in the comments.

2024-12-16 15:43 UTC, charles-lunarg commented on cube/cube.cpp
> +            // select physical device because display surface creation need gpu is selected.
```suggestion
           // select physical device because display surface creation needs a gpu to be selected.
```

2024-12-16 15:43 UTC, charles-lunarg commented on cube/cube.c
> +            // select physical device because display surface creation need gpu is selected.
```suggestion
            // select physical device because display surface creation needs a gpu to be selected.
```

2024-12-16 19:09 UTC, water-chika commented
Thanks, I have commited the your fixes and I will squash the commits to 1 commit.

2024-12-16 19:25 UTC, charles-lunarg approved these changes
Looks great, thank you.
And squashing would be very much appreciated :)

2024-12-17 06:00 UTC, water-chika commented
It seems that I could not merge PR. It shows only those with write access to this repository can merge pull requests.
@charles-lunarg, could you please help to squash commits and merge it?

Thanks,

2025-04-04 18:28 UTC, mairacanal commented
Any update on this PR? I was able to reproduce issue #1056 as well, and this PR fixed it.

2025-04-07 15:15 UTC, charles-lunarg approved these changes
Vulkan-Tools fell off my radar for a bit. Apologies! I will try to work through this backlog.

2025-04-07 15:15 UTC, merged