Fixed paths for MoltenVK changes
KhronosGroup/Vulkan-Tools pull request #451
Opened 2020-09-28 18:58 UTC by richard-lunarg

Minor changes to cmake files for macOS only builds. Changes to MoltenVK required some simple path changes to locate the dynamic library.

2020-09-28 18:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-Tools?pullRequest=451) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-Tools?pullRequest=451) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-Tools?pullRequest=451) it.</sub>

2020-09-28 19:20 UTC, jeremyk-lunarg requested changes
This change requires an update to the version of MoltenVK in `known_good.json`.

2020-09-29 01:56 UTC, richard-lunarg commented
known_good.json updated.

2020-09-29 13:45 UTC, jeremyk-lunarg approved these changes
Builds now.
LGTM

2020-09-29 17:03 UTC, merged